pipeline {
  agent any
  environment {
    APP_PORT = "5000"
    GIT_BRANCH = "${env.BRANCH_NAME}"
  }
  stages {
    stage('Install dependencies') {
      steps {
        sh 'pip install -r requirements.txt'
      }
    }
    stage('Test') {
      steps {
        sh 'pytest'
      }
    }
    stage('Deploy to Dev') {
      when {
        branch 'dev'
      }
      steps {
        sh 'gunicorn app:app -b 0.0.0.0:${APP_PORT} -w 4 -k gthread &'
      }
    }
    stage('Deploy to Prod') {
      when {
        branch 'main'
      }
      steps {
        sh 'gunicorn app:app -b 0.0.0.0:${APP_PORT} -w 4 -k gthread &'
      }
    }
  }
}
